
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HTTP_PORT: 8080
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: INFO
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    ports:
      - "8080:8080"

    networks:
      - my-network
    command: ["start-dev","--import-realm"] 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  blog-app:
    build:
      context: ./	 # Path to blogapp application's Dockerfile
    container_name: blog-app
    ports:
      - "9090:9090" # Map host port 9090 to Tomcat's 9090
    depends_on:
      - keycloak
    networks:
      - my-network

networks:
  my-network:
    driver: bridge